name: network-overrides

on:
  workflow_dispatch:
    # manual trigger
  push:
    # on push to any branch, excluding our generated ones
    branches-ignore:
      - "x-build/*"

  # PR not needed since push is enough?

  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    # TODO use from network-overrides
    # uses:

    runs-on: ubuntu-latest

    env:
      BUILD_CMD: npm run build
      BUILD_DIR: build/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: |
          git config --global user.email "network-overrides@example.com"
          git config --global user.name "Network Overrides"

      - run: npm i

      - run: |
          BRANCH="$(git branch --show-current)"
          BUILD_BRANCH="x-build/$BRANCH"

          # # https://stackoverflow.com/a/31914717/9285308
          # if git rev-parse --quiet --verify "$BUILD_BRANCH"; then
          #   git checkout "$BUILD_BRANCH"
          #   git pull --rebase
          # else
          #   git checkout -b "$BUILD_BRANCH"
          # fi
          #
          # # git reset --hard "$BRANCH"

          git branch "$BUILD_BRANCH" --force HEAD
          git checkout "$BUILD_BRANCH"

          bash -c "$BUILD_CMD"

          # TMP_BUILD_DIR="$(mktemp -d)"
          # mv "$BUILD_DIR" "$TMP_BUILD_DIR"
          # rm -rf * .*

          BRANCH_COMMIT="$(git rev-parse "$BRANCH")"
          # TODO maybe add "[skip ci]" to message body?
          COMMIT_MSG="build $BRANCH_COMMIT from $BRANCH"

          git add "$BUILD_DIR"
          BUILD_TREE="$(git write-tree --prefix "$BUILD_DIR")"
          BUILD_TREE_COMMIT="$(git commit-tree "$BUILD_TREE" -m "$COMMIT_MSG")"
          git reset --hard "$BUILD_TREE_COMMIT"

          git -c push.autoSetupRemote=true push --force
